image:
  file: .gitpod.Dockerfile
tasks:
  - name: persist env
    command: eval $(gp env -e)
  - name: Configure AWS Profile
    command: |
      echo "[gitpod]" >> ~/.aws/config
      echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config
      echo "cli_auto_prompt = on-partial" >> ~/.aws/config
      echo "[gitpod]" >> ~/.aws/credentials
      echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
      echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  - name: CDK bootstrap
    command: cdk bootstrap aws://$AWS_ACCOUNT_NUMBER/$AWS_DEFAULT_REGION
  - name: Configure KubeConfig
    command: echo $K8S_CONFIG | base64 -d > ~/.kube/config
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - amazonwebservices.aws-toolkit-vscode
    - rangav.vscode-thunder-client
    - ms-python.python
    - ms-toolsai.jupyter
