image: aymanzahran/ipad-gitpod-image
  #file: .gitpod.Dockerfile
tasks:
  - name: persist env
    command: eval $(gp env -e)
  - name: Configure AWS Profile
    command: |
      echo "[gitpod]" > ~/.aws/config
      echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config
      echo "cli_auto_prompt = on-partial" >> ~/.aws/config
      echo "[gitpod]" > ~/.aws/credentials
      echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
      echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  # - name: Configure Ansible and Jenkins
  #   command: |
  #     echo $ID_RSA | base64 -d > ~/id_rsa
  #     echo $ID_RSA_PUB | base64 -d > ~/id_rsa.pub
  #     docker-compose build
  #     docker compose up AnsibleController AnsibleTarget1 AnsibleTarget2 Jenkins
  - name: Launch Okteto
    command: okteto up
  - name: Configure KubeConfig
    command: echo $K8S_CONFIG | base64 -d > ~/.kube/config
  - name: Configure KubeConfig
    command: flux bootstrap github --owner=$GITPOD_GIT_USER_NAME --repository=IpadGitpodWorkspace --branch=master --path=../Flux/ --personal
  
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - amazonwebservices.aws-toolkit-vscode
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - hashicorp.terraform
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - ms-python.python
    - rangav.vscode-thunder-client
    - PKief.material-icon-theme