image: aymanzahran/ipad-gitpod-image
  #file: .gitpod.Dockerfile
tasks:
  - name: persist env
    command: eval $(gp env -e)
  - name: Configure AWS Profile
    command: |
      echo "[gitpod]" > ~/.aws/config
      echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config
      echo "cli_auto_prompt = on-partial" >> ~/.aws/config
      echo "[gitpod]" > ~/.aws/credentials
      echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
      echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  - name: Configure K8s
    command: echo $K8S_CONFIG | base64 --decode > ~/.kube/config
  - name: Authenticate Digital Ocean
    command: |
      mkdir -p ~/.config/doctl
      echo "access-token: $DIGITAL_OCEAN_TOKEN" > ~/.config/doctl/config.yaml
  - name: Launch kubernetes-dashboard
    command: |
      helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
      helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard
      helm upgrade kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard
      export POD_NAME=$(kubectl get pods -n default -l "app.kubernetes.io/name=kubernetes-dashboard,app.kubernetes.io/instance=kubernetes-dashboard" -o jsonpath="{.items[0].metadata.name}")
      echo https://127.0.0.1:8443/
      kubectl -n default port-forward $POD_NAME 8443:8443
  - name: Launch metrics-server
    command: |
      helm repo add bitnami https://charts.bitnami.com/bitnami
      helm install my-release bitnami/metrics-server
  - name: Launch kube-prometheus-stack
    command: |
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update
      helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack
      helm upgrade prometheus-operator prometheus-community/kube-prometheus-stack 
      sleep 10
      kubectl port-forward svc/kube-prometheus-stack-prometheus 9090:9090
      kubectl port-forward svc/kube-prometheus-stack-grafana 3000:80
  - name: Launch Jenkins
    command: |
      kubectl apply -f Kubernetes/jenkins-master.yaml
      sleep 10
      kubectl port-forward service/jenkins-master 8081:80
  - name: Launch Ansible Controller
    command: |
      kubectl apply -f Kubernetes/ansible-controller.yaml
      sleep 10
      kubectl port-forward service/ansible-controller 8082:80
  - name: Launch Ansible Target
    command: |
      kubectl apply -f Kubernetes/ansible-target.yaml
      sleep 10
      kubectl port-forward service/ansible-target 8083:80
  - name: Launch NGINX Controller
    command: |
      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      helm repo update
      helm install nginx-ingress ingress-nginx/ingress-nginx
      helm upgrade nginx-ingress ingress-nginx/ingress-nginx
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - amazonwebservices.aws-toolkit-vscode
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - hashicorp.terraform
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - ms-python.python
    - rangav.vscode-thunder-client
    - PKief.material-icon-theme
