image: aymanzahran/cloud-development:latest
  #file: .gitpod.Dockerfile
tasks:
  - name: persist env
    command: eval $(gp env -e)
  - name: Configure AWS Profile
    command: |
      echo "[gitpod]" >> ~/.aws/config
      echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config
      echo "cli_auto_prompt = on-partial" >> ~/.aws/config
      echo "[gitpod]" >> ~/.aws/credentials
      echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
      echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - amazonwebservices.aws-toolkit-vscode
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - hashicorp.terraform
    - eg2.vscode-npm-script
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - ms-python.python
    - rangav.vscode-thunder-client
    - PKief.material-icon-theme
