version: "3.8"
services:
  AnsibleController:
    image: shellwhale/ansible
    hostname: AnsibleController
    tty: true
    volumes:
      - ./Ansible:/Ansible
    build:
      context: .
      dockerfile: Dockerfile.AnsibleController
  AnsibleTarget1:
    hostname: AnsibleTarget1
    image: shellwhale/centos
    build:
      context: .
      dockerfile: Dockerfile.AnsibleTarget
  AnsibleTarget2:
    hostname: AnsibleTarget2
    image: shellwhale/centos
    build:
      context: .
      dockerfile: Dockerfile.AnsibleTarget
