version: "3.8"
services:
  AnsibleController:
    image: ansible-controller
    hostname: AnsibleController
    tty: true
    volumes:
      - ./Ansible:/Ansible
    build:
      context: .
      dockerfile: Dockerfile.AnsibleController
  AnsibleTarget1:
    image: ansible-target
    hostname: AnsibleTarget1
    ports:
      - "999:80"
    build:
      context: .
      dockerfile: Dockerfile.AnsibleTarget
  AnsibleTarget2:
    image: ansible-target
    hostname: AnsibleTarget2
    build:
      context: .
      dockerfile: Dockerfile.AnsibleTarget
  Jenkins:
    image: jenkins
    hostname: Jenkins
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile.Jenkins
    environment:
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "password"
