version: "3.8"
services:
  AnsibleController:
    image: aymanzahran/ipad-ansiblecontroller-image
    hostname: ansible-controller
    tty: true
    volumes:
      - ./Ansible:/Ansible
    # build:
    #   context: .
    #   dockerfile: Dockerfile.AnsibleController
  AnsibleTarget1:
    image: aymanzahran/ipad-ansibletarget-image
    hostname: ansible-target-1
    ports:
      - "999:80"
    # build:
    #   context: .
    #   dockerfile: Dockerfile.AnsibleTarget
  AnsibleTarget2:
    image: aymanzahran/ipad-ansibletarget-image
    hostname: ansible-target-2
    # build:
    #   context: .
    #   dockerfile: Dockerfile.AnsibleTarget
  Jenkins:
    image: aymanzahran/ipad-jenkins-image
    hostname: jenkins
    ports:
      - "8080:8080"
    # build:
    #   context: .
    #   dockerfile: Dockerfile.Jenkins
    environment:
      JENKINS_USERNAME: "admin"
      JENKINS_PASSWORD: "password"
