version: "3.8"
services:
  ansible-controller:
    image: aymanzahran/ipad-ansiblecontroller-image
    hostname: ansible-controller
    tty: true
    volumes:
      - 
      
      
    # build:
    #   context: .
    #   dockerfile: Dockerfile.AnsibleController
  ansible-target-1:
    image: aymanzahran/ipad-ansibletarget-image
    hostname: ansible-target-1
    ports:
      - "999:80"
    # build:
    #   context: .
    #   dockerfile: Dockerfile.AnsibleTarget
  ansible-target-2:
    image: aymanzahran/ipad-ansibletarget-image
    hostname: ansible-target-2
    # build:
    #   context: .
    #   dockerfile: Dockerfile.AnsibleTarget
  jenkins:
    image: aymanzahran/ipad-jenkins-image
    hostname: jenkins
    ports:
      - "8080:8080"
    # build:
    #   context: .
    #   dockerfile: Dockerfile.Jenkins
    environment:
      JENKINS_USERNAME: "admin"
      JENKINS_PASSWORD: "password"
