# https://www.digitalocean.com/community/tutorials/how-to-automate-jenkins-setup-with-docker-and-jenkins-configuration-as-code
# https://www.jenkins.io/projects/jcasc/
# https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md#getting-started
FROM jenkins/jenkins:latest
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
COPY Jenkins/plugins.txt /usr/share/jenkins/ref/plugins.txt
# RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt (DEPRECIATED)
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
COPY Jenkins/casc.yaml /var/jenkins_home/casc.yaml