apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-goodbye
spec:
  params:
  - name: username
    type: string
  tasks:
    - name: hi
      taskRef:
        name: hi
    - name: goodbye
      runAfter:
        - hi
      taskRef:
        name: goodbye
      params:
      - name: username
        value: $(params.username)