- hosts: webservers
  vars:
      http_port: 999
      server_name: "web"
      message: "Hello world"
  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: present

    - name: Start the httpd server
      shell: /usr/sbin/httpd

    - name: Add the index.html
      template:
        src: index.html
        dest: /usr/share/httpd/noindex/index.html

  handlers:
    - name: Restart the httpd server
      shell: pkill httpd && /usr/sbin/httpd

- hosts: dbservers
  tasks:
    - name: Install mariadb-server
      yum:
        name: mariadb-server
        state: present
