- hosts: webservers
  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: present

    - name: Add the index.html
      template:
        src: index.html
        dest: /var/www/html/index.html

- hosts: dbservers
  tasks:
    - name: Install mariadb-server
      yum:
        name: mariadb-server
        state: present
