name: BuildPushAnsibleTargetImage

on:   
  schedule:
    - cron: 0 1 * * *
  pull_request:
    branches:
      - master

jobs:
  BuildPushAnsibleTargetImageToGHCR:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Get RSA Public Key
        run: echo $ID_RSA_PUB | base64 -d > ~/id_rsa.pub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleTarget
          push: true
          tags: ghcr.io/${{ secrets.GITHUB_USER }}/${{ secrets.ANSIBLE_TARGET_IMAGE_NAME}}
  
  BuildPushAnsibleTargetImageToDockerHub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get RSA Private Key
        run: echo $ID_RSA | base64 -d > ~/id_rsa
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleTarget
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.ANSIBLE_TARGET_IMAGE_NAME}}
