name: BuildPushAnsibleControllerImage

on:   
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
    tags:
      - v*
env:
  ANSIBLE_CONTROLLER_IMAGE_NAME: ipad-ansiblecontroller-image

jobs:
  BuildPushAnsibleControllerImageToGHCR:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleController
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.ANSIBLE_CONTROLLER_IMAGE_NAME}}
  
  BuildPushAnsibleControllerImageToDockerHub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleController
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ANSIBLE_CONTROLLER_IMAGE_NAME}}
