name: Configuration

on:
  push:
    branches:
      - master
    paths:
      - Configuration/**
  pull_request:
    branches:
      - master
    paths:
      - Configuration/**

jobs:
  ScanValidateConfigurations:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Configuration
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: ls
      -   name: Run Analysis
          uses: codescan-io/codescan-scanner-action@master
          with:
            login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
            organization: ${{ secrets.CODESCAN_ORGANIZATION_KEY }}
            projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}
            args: |
              sonar.verbose=true
              sonar.java.binaries=target
      - name: Kubeval
        uses: instrumenta/kubeval-action@master
        with:
          files: Configuration
      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
        with:
          input: ansible-controller.yaml
          format: template
          template: template/sarif.tpl
          output: kubesec-results.sarif
          exit-code: "0"
      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kubesec-results.sarif
