name: DockerImageBuild

on:   
  push:
    branches:
      - master
    tags:
      - v*
env:
  GITPOD_IMAGE_NAME: ipad-gitpod-image
  JENKINS_IMAGE_NAME: ipad-jenkins-image
  ANSIBLE_CONTROLLER_IMAGE_NAME: ipad-ansiblecontroller-image
  ANSIBLE_TARGET_IMAGE_NAME: ipad-ansibletarget-image

jobs:
  BuildGitpodImage:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . --file tmp.Dockerfile --tag $GITPOD_IMAGE_NAME
      
      - name: Log in to GHCR registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push To GHCP
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$GITPOD_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $GITPOD_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      
      - name: Log in to Docker Hub
        run: docker login --username aymanzahran --password $$DOCKERHUB_PERSONAL_ACCESS_TOKEN

      - name: Push To Dockerhub
        run: |
          IMAGE_ID=${{ github.repository_owner }}/$GITPOD_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $GITPOD_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
  
  BuildJenkinsImage:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . --file tmp.Dockerfile
      
      - name: Log in to GHCR registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push To GHCP
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$JENKINS_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $JENKINS_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      
      - name: Log in to Docker Hub
        run: docker login --username aymanzahran --password $$DOCKERHUB_PERSONAL_ACCESS_TOKEN

      - name: Push To Dockerhub
        run: |
          IMAGE_ID=${{ github.repository_owner }}/$JENKINS_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $JENKINS_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID

  BuildAnsibleControllerImage:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . --file tmp.Dockerfile
      
      - name: Push To GHCP
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$ANSIBLE_CONTROLLER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $ANSIBLE_CONTROLLER_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      
      - name: Log in to Docker Hub
        run: docker login --username aymanzahran --password $$DOCKERHUB_PERSONAL_ACCESS_TOKEN

      - name: Push To Dockerhub
        run: |
          IMAGE_ID=${{ github.repository_owner }}/$ANSIBLE_CONTROLLER_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $ANSIBLE_CONTROLLER_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID

  BuildAnsibleTargetImage:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . --file tmp.Dockerfile
      
      - name: Push To GHCP
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$ANSIBLE_TARGET_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $ANSIBLE_TARGET_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      
      - name: Log in to Docker Hub
        run: docker login --username aymanzahran --password $$DOCKERHUB_PERSONAL_ACCESS_TOKEN

      - name: Push To Dockerhub
        run: |
          IMAGE_ID=${{ github.repository_owner }}/$ANSIBLE_TARGET_IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          docker tag $ANSIBLE_TARGET_IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
