name: DockerImageBuildPush

on:   
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
    tags:
      - v*
env:
  GITPOD_IMAGE_NAME: ipad-gitpod-image
  JENKINS_IMAGE_NAME: ipad-jenkins-image
  ANSIBLE_CONTROLLER_IMAGE_NAME: ipad-ansiblecontroller-image
  ANSIBLE_TARGET_IMAGE_NAME: ipad-ansibletarget-image

jobs:
  BuildPushGitpodImageToGHCR:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.JENKINS_IMAGE_NAME}}
  
  BuildPushGitpodImageToDockerHub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.JENKINS_IMAGE_NAME}}
  
  BuildPushJenkinsImageToGHCR:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.Jenkins
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.JENKINS_IMAGE_NAME}}

  BuildPushJenkinsImageToDockerHub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.Jenkins
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.JENKINS_IMAGE_NAME}}

  BuildPushAnsibleControllerImageToGHCR:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleController
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.ANSIBLE_CONTROLLER_IMAGE_NAME}}
  
  BuildPushAnsibleControllerImageToDockerHub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleController
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ANSIBLE_CONTROLLER_IMAGE_NAME}}

  BuildPushAnsibleTargetImageToGHCR:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleTarget
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ env.ANSIBLE_TARGET_IMAGE_NAME}}
  
  BuildPushAnsibleTargetImageToDockerHub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.AnsibleTarget
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ANSIBLE_TARGET_IMAGE_NAME}}
