name: KubevalScan

on:
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  KubevalScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: instrumenta/kubeval-action@master
        with:
          files: Kubernetes
