name: OktetoApply

on:
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  OktetoApplyJenkins:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: config
      run: echo ${{ secrets.K8S_CONFIG }} | base64 --decode > KUBECONFIG
    - name: deploy jenkins master
      run: kubectl apply -f Kubernetes/jenkins-master.yaml --kubeconfig=KUBECONFIG

  OktetoApplyAnsibleController:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: actions-hub/kubectl@master
      continue-on-error: true
      env:
        KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
      with:
        args: apply -f Kubernetes/ansible-controller.yaml
  
  OktetoApplyAnsibleTarget:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: actions-hub/kubectl@master
      continue-on-error: true
      env:
        KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
      with:
        args: apply -f Kubernetes/ansible-target.yaml
