name: OktetoApply

on:
  schedule:
    - cron: 0 1 * * *
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  OktetoApplyJenkins:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
      with:
        args: apply -f Kubernetes/jenkins-master.yaml

  OktetoApplyAnsibleController:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
      with:
        args: apply -f Kubernetes/anisble-controller.yaml
  
  OktetoApplyAnsibleTarget:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
      with:
        args: apply -f Kubernetes/anisble-target.yaml
